# frontend/Dockerfile.dev

FROM node:18-alpine
WORKDIR /app

# 의존성 설치
COPY package.json .
COPY package-lock.json .
RUN npm install

# 소스 복사
COPY . .

# 개발 서버 포트 열기
EXPOSE 3000

# 개발 서버 실행 (Hot Reload)
CMD ["npm", "start"]
